// This file contains a curated list of top video game publishers from various segments of the gaming industry.
export const TOP_PUBLISHERS = [
  // AAA Gaming Giants
  "Electronic Arts",
  "Activision Blizzard",
  "Ubisoft",
  "Sony Interactive Entertainment",
  "Microsoft Studios",
  "Nintendo",
  "Take-Two Interactive",
  "Valve Corporation",

  // Major Publishers
  "Bethesda Softworks",
  "Square Enix",
  "Capcom",
  "Konami",
  "Sega",
  "Bandai Namco",
  "Warner Bros. Games",
  "Deep Silver",
  "Focus Entertainment",
  "THQ Nordic",

  // Popular Indie/Mid-tier Publishers
  "Devolver Digital",
  "Annapurna Interactive",
  "Raw Fury",
  "Team17",
  "Humble Bundle",
  "Good Old Games",
  "Paradox Interactive",
  "Fireshine Games",
  "Curve Digital",

  // Gaming Platform Publishers
  "Steam",
  "Epic Games",
  "GOG.com",
  "Origin",
  "Battle.net",
  "PlayStation Store",
  "Xbox Game Pass",
  "Nintendo eShop",
  "Itch.io",
  "GameJolt",

  // Regional Powerhouses
  "Tencent Games",
  "NetEase Games",
  "Nexon",
  "NCSoft",
  "Krafton",
  "miHoYo",
  "Supercell",
  "King Digital Entertainment",
  "Gameloft",
  "DeNA",

  // Western Indies & Publishers
  "Coffee Stain Publishing",
  "Wired Productions",
  "Merge Games",
  "Red Hook Studios",
  "Klei Entertainment",
  "Subset Games",
  "Unknown Worlds Entertainment",
  "Motion Twin",
  "Playdead",
  "Supergiant Games",

  // More AAA & Major Studios
  "Rockstar Games",
  "CD Projekt",
  "Blizzard Entertainment",
  "Riot Games",
  "Bungie",
  "Epic Games Publishing",
  "2K Games",
  "Activision Publishing",

  // Established Publishers
  "LucasArts",
  "Sierra Entertainment",
  "Midway Games",
  "Atari",
  "Acclaim Entertainment",
  "Eidos Interactive",
  "3D Realms",
  "id Software",
  "Valve",
  "Gearbox Publishing",

  // Modern Publishers & Distributors
  "Scholastic",
  "Nacon",
  "Microids",
  "Kalypso Media",
  "Kasedo Games",
  "HandyGames",
  "Headup Games",
  "Daedalic Entertainment",
  "Artifex Mundi",

  // Additional Notable Publishers
  "Codemasters",
  "Sports Interactive",
  "Creative Assembly",
  "Playground Games",
  "Rare Ltd.",
  "Mojang Studios",
  "343 Industries",
  "The Coalition",
  "Guerrilla Games",
  "Naughty Dog",
  "Santa Monica Studio",
  "Insomniac Games",
  "Sucker Punch Productions",
  "Housemarque",
  "Bluepoint Games",

  // More Quality Publishers
  "Respawn Entertainment",
  "DICE",
  "BioWare",
  "Obsidian Entertainment",
  "InXile Entertainment",
  "Double Fine",
  "Ninja Theory",
  "Compulsion Games",
  "Undead Labs",
  "The Initiative",
  "World's Edge",
  "Turn 10 Studios",
];
